apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myservice
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/erickbitso/canary-deployment-test.git
    targetRevision: HEAD
    path: scenario
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  ignoreDifferences:
      - group: ""
        kind: Service
        managedFieldsManagers:
          - rollouts-controller
      - group: networking.istio.io
        kind: VirtualService
        managedFieldsManagers:
          - rollouts-controller
      - group: argoproj.io
        jqPathExpressions:
          - .spec.template.spec.containers[] | .livenessProbe.grpc.service
          - .spec.template.spec.containers[] | .readinessProbe.grpc.service
          - .spec.template.spec.containers[] | .startupProbe.grpc.service
  syncPolicy:
      automated:
          allowEmpty: true
          prune: true
          selfHeal: true
      retry:
          backoff:
              duration: 5s
              factor: 2
              maxDuration: 3m
          limit: 5
      syncOptions:
          - Validate=false
          - RespectIgnoreDifferences=true
          - PruneLast=true
