apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: service-b
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: service-b
  minReplicaCount: 3
  maxReplicaCount: 5
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "50"
