apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifest.yaml
commonAnnotations:
  bitso.com/entity-repository-name: service-b
  bitso.com/config-git-commit: green
  bitso.com/entity-deployment-config-path: deployments/service-b
commonLabels: {}
patches:
  - target:
      kind: Deployment
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SERVER_PORT
          value: "8080"
  - target:
      kind: Rollout
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SERVER_PORT
          value: "8080"
images:
  - name: service-b
    newName: service-b
    newTag: green
generatorOptions:
  disableNameSuffixHash: true
  labels:
    bitso/generated-by: environment-transformation
