apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: service-b
spec:
  strategy:
    canary:
      canaryService: service-b-canary
      stableService: service-b-stable
      trafficRouting:
        istio:
          virtualServices:
          - name: service-b
            routes:
            - primary
          - name: service-b-internal
            routes:
            - primary-http
            #- primary-grpc
      steps:
        - setWeight: 10
        - pause: {}
        - setWeight: 40
        - pause: {}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
        istio-injection: enabled
    spec:
      containers:
      - name: service-b
        image: service-b:blue
        imagePullPolicy: Never
        ports:
        - name: grpc
          containerPort: 8201
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 50m

